# Generated by Django 3.2.7 on 2021-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimming', '0002_add_ordering_by_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmingcompetition',
            name='start_date',
            field=models.DateField(),
        ),
    ]
